// server/src/models/Task.js

const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema(
  {
    // Task title - the only strictly required user-facing field
    title: {
      type: String,
      required: [true, 'Task title is required'],
      trim: true,
    },

    // Optional longer description of the task
    description: {
      type: String,
      trim: true,
      default: '',
    },

    // Current column the task belongs to on the Kanban board
    status: {
      type: String,
      enum: ['todo', 'inprogress', 'done'],
      default: 'todo',
    },

    // Priority level shown as a badge on the task card
    priority: {
      type: String,
      enum: ['low', 'medium', 'high'],
      default: 'medium',
    },

    // The team member this task is assigned to (optional)
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    // The team this task belongs to (every task must belong to a team)
    team: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Team',
      required: true,
    },

    // The user who created this task
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // Flag to mark tasks that were auto-generated by AI from a transcript
    // Not used yet - will power a badge in the UI once AI extraction is built
    isAIGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true, // adds createdAt and updatedAt automatically
  }
);

module.exports = mongoose.model('Task', taskSchema);